apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: catalog
  name: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: docker.io/ewolff/microservice-kubernetes-demo-catalog:latest
        ports:
        - containerPort: 8080

---


apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: customer
  name: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - name: customer
        image: docker.io/ewolff/microservice-kubernetes-demo-customer:latest
        ports:
        - containerPort: 8080

---


apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: order
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: docker.io/ewolff/microservice-kubernetes-demo-order:latest
        ports:
        - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: catalog
  name: catalog
spec:
  selector:
    app: catalog
  ports:
  - port: 80
    targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: order
  name: order
spec:
  selector:
    app: order
  ports:
  - port: 80
    targetPort: 8080

---


apiVersion: v1
kind: Service
metadata:
  labels:
    app: customer
  name: customer
spec:
  selector:
    app: customer
  ports:
  - port: 80
    targetPort: 8080

